// Package consts
// @Author: zhangdi
// @File: colors
// @Version: 1.0.0
// @Date: 2022/9/13 10:43
package utilcolor

// Colors 颜色16进制代码
const (
	ColorGreen             string = "#008000"
	ColorRed               string = "#FF0000"
	ColorOlive             string = "#808000"
	ColorOrange            string = "#FFA500"
	ColorBlue              string = "#0000FF"
	ColorGray              string = "#808080"
	ColorBlack             string = "#000000"
	ColorWhite             string = "#FFFFFF"
	ColorYellow            string = "#FFFF00"
	ColorTeal              string = "#008080"
	ColorNavy              string = "#000080"
	ColorMaroon            string = "#800000"
	ColorSilver            string = "#C0C0C0"
	ColorLime              string = "#00FF00"
	ColorFuchsia           string = "#FF00FF"
	ColorAqua              string = "#00FFFF"
	ColorRoyalBlue         string = "#4169E1"
	ColorDeepSkyBlue       string = "#00BFFF"
	ColorDodgerBlue        string = "#1E90FF"
	ColorSteelBlue         string = "#4682B4"
	ColorCornflowerBlue    string = "#6495ED"
	ColorLightSlateGray    string = "#778899"
	ColorSlateGray         string = "#708090"
	ColorDarkSlateGray     string = "#2F4F4F"
	ColorLightSeaGreen     string = "#20B2AA"
	ColorMediumTurquoise   string = "#48D1CC"
	ColorTurquoise         string = "#40E0D0"
	ColorAquamarine        string = "#7FFFD4"
	ColorMediumAquamarine  string = "#66CDAA"
	ColorMediumSpringGreen string = "#00FA9A"
	ColorMintCream         string = "#F5FFFA"
	ColorSpringGreen       string = "#3CB371"
	ColorMediumSeaGreen    string = "#3CB371"
	ColorSeaGreen          string = "#2E8B57"
	ColorHoneydew          string = "#F0FFF0"
	ColorPaleGreen         string = "#98FB98"
	ColorLightGreen        string = "#90EE90"
	ColorDarkSeaGreen      string = "#8FBC8F"
	ColorLavender          string = "#E6E6FA"
	ColorThistle           string = "#D8BFD8"
	ColorViolet            string = "#EE82EE"
	ColorPlum              string = "#DDA0DD"
	ColorOrchid            string = "#DA70D6"
	ColorMagenta           string = "#FF00FF"
	ColorMediumOrchid      string = "#BA55D3"
	ColorMediumPurple      string = "#9370DB"
	ColorBlueViolet        string = "#8A2BE2"
	ColorDarkViolet        string = "#9400D3"
	ColorDarkOrchid        string = "#9932CC"
	ColorDarkMagenta       string = "#8B008B"
	ColorPurple            string = "#800080"
	ColorIndigo            string = "#4B0082"
)
